//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPR_CNAS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DPR_CNAS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %PDF-1.4        ///%âăĎÓ
        ///608 0 obj        ///&lt;&lt;/Linearized 1/L 3850515/O 611/E 194487/N 109/T 3838307/H [ 8756 3256]&gt;&gt;        ///endobj        ///       
        ///xref
        ///608 423
        ///0000000016 00000 n
        ///0000012012 00000 n
        ///0000012111 00000 n
        ///0000012155 00000 n
        ///0000012346 00000 n
        ///0000017899 00000 n
        ///0000018043 00000 n
        ///0000018770 00000 n
        ///0000018920 00000 n
        ///0000019625 00000 n
        ///0000019896 00000 n
        ///0000019999 00000 n
        ///0000020319 00000 n
        ///0000020602 00000 n
        ///0000020928 00000 n
        ///0000021944 00000 n
        ///0000022534 00000 n
        ///0000023051 00000 n
        ///0000023520 00000 n
        ///0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GhidDiabetic {
            get {
                return ResourceManager.GetString("GhidDiabetic", resourceCulture);
            }
        }
    }
}
